# Generated by Django 3.2.12 on 2025-07-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ImageField(default=1, upload_to='news_images/'),
            preserve_default=False,
        ),
    ]
