# Generated by Django 5.2.4 on 2025-07-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintproduct',
            name='image',
            field=models.ImageField(upload_to='products/products/'),
        ),
    ]
