# Generated by Django 4.2.11 on 2025-07-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_orderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
