# Generated by Django 5.2.2 on 2025-07-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orderrequest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
