# Generated by Django 5.2.2 on 2025-07-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_footwearproduct_furnitureproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footwearorderrequest',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('qabul_qilingan', 'Qabul qilingan'), ('jarayonda', 'Jarayonda'), ('tayyor', 'Tayyor')], default='yangi', max_length=20),
        ),
        migrations.AddField(
            model_name='furnitureorderrequest',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('qabul_qilingan', 'Qabul qilingan'), ('jarayonda', 'Jarayonda'), ('tayyor', 'Tayyor')], default='yangi', max_length=20),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('qabul_qilingan', 'Qabul qilingan'), ('jarayonda', 'Jarayonda'), ('tayyor', 'Tayyor')], default='yangi', max_length=20),
        ),
    ]
