# Generated by Django 3.2.12 on 2025-07-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_footwearorderrequest_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footwearorderrequest',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='furnitureorderrequest',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='is_seen',
        ),
    ]
