# Generated by Django 3.2.12 on 2025-07-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20250721_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footwearorderrequest',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='furnitureorderrequest',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='orderrequest',
            name='is_processed',
        ),
    ]
