# Generated by Django 3.2.12 on 2025-07-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20250721_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwearorderrequest',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('qabul_qilingan', 'Qabul qilingan'), ('bekor_qilingan', 'Bekor qilingan')], default='yangi', max_length=20),
        ),
        migrations.AlterField(
            model_name='furnitureorderrequest',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('qabul_qilingan', 'Qabul qilingan'), ('bekor_qilingan', 'Bekor qilingan')], default='yangi', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('qabul_qilingan', 'Qabul qilingan'), ('bekor_qilingan', 'Bekor qilingan')], default='yangi', max_length=20),
        ),
    ]
